// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

// const SUPABASE_URL = "https://ddnewessrxcfvnclkmvc.supabase.co";
const SUPABASE_URL = "https://lifefmjlnanrrbafwqll.supabase.co";
// const SUPABASE_PUBLISHABLE_KEY =
//   "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRkbmV3ZXNzcnhjZnZuY2xrbXZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyMzU5MDQsImV4cCI6MjA2MDgxMTkwNH0.jeXFnWw0dlz3xKNlxt3NX3vfFUdQ5ebTaBXN2hR6XaU";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxpZmVmbWpsbmFucnJiYWZ3cWxsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwMzA2NjcsImV4cCI6MjA2MzYwNjY2N30.iusxdQs8DZLx_2ySVW_3KaRFFkgP86-cRzmaC5GFK6E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
      storageKey: "kolekto-auth-token",
    },
  }
);
